# Generated by Django 4.1.2 on 2022-11-10 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_delete_bid_delete_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='activeListing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.CharField(default='', max_length=2090),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
